name: Tweet when app finishes running
on:
  release:
    types: [published]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set tweet message
      run: echo "TWEET_MESSAGE=$(python -c 'import os; print(os.environ["TWEET_MESSAGE"])')" >> $GITHUB_ENV

    - name: Send tweet
      uses: ethomson/send-tweet-action@v1
      with:
        status: ${{ env.TWEET_MESSAGE }}
        consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
        consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
